<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
    <PackageVersion Include="Scrutor" Version="7.0.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="4.0.1" />
  </ItemGroup>
</Project>
