<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\CQRSlite\CQRSlite.csproj" />
    <ProjectReference Include="..\CQRSCode\CQRSCode.csproj" />
  </ItemGroup>

</Project>
